// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradeHelper.Data;

#nullable disable

namespace TradeHelperAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260303145103_AddEdgeFinderTables")]
    partial class AddEdgeFinderTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TradeHelper.Models.BrokerImportHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrokerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImportNotes")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TradesFailed")
                        .HasColumnType("int");

                    b.Property<int>("TradesImported")
                        .HasColumnType("int");

                    b.Property<int>("TradesSkipped")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("BrokerImportHistories");
                });

            modelBuilder.Entity("TradeHelper.Models.COTReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("CommercialLong")
                        .HasColumnType("bigint");

                    b.Property<long>("CommercialShort")
                        .HasColumnType("bigint");

                    b.Property<long>("NonCommercialLong")
                        .HasColumnType("bigint");

                    b.Property<long>("NonCommercialShort")
                        .HasColumnType("bigint");

                    b.Property<long>("OpenInterest")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "ReportDate");

                    b.ToTable("COTReports");
                });

            modelBuilder.Entity("TradeHelper.Models.EconomicHeatmapEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("DateCollected")
                        .HasColumnType("datetime2");

                    b.Property<string>("Impact")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Indicator")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("PreviousValue")
                        .HasColumnType("float");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Currency", "Indicator");

                    b.ToTable("EconomicHeatmapEntries");
                });

            modelBuilder.Entity("TradeHelper.Models.EdgeFinderScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bias")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("COTScore")
                        .HasColumnType("float");

                    b.Property<string>("DataSources")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("DateComputed")
                        .HasColumnType("datetime2");

                    b.Property<double>("EconomicScore")
                        .HasColumnType("float");

                    b.Property<double>("FundamentalScore")
                        .HasColumnType("float");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int");

                    b.Property<double>("OverallScore")
                        .HasColumnType("float");

                    b.Property<double>("RetailSentimentScore")
                        .HasColumnType("float");

                    b.Property<double>("SentimentScore")
                        .HasColumnType("float");

                    b.Property<double>("TechnicalScore")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId", "DateComputed");

                    b.ToTable("EdgeFinderScores");
                });

            modelBuilder.Entity("TradeHelper.Models.IndicatorData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("COTScore")
                        .HasColumnType("float");

                    b.Property<double>("CPI")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateCollected")
                        .HasColumnType("datetime2");

                    b.Property<double>("EmploymentChange")
                        .HasColumnType("float");

                    b.Property<double>("GDP")
                        .HasColumnType("float");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int");

                    b.Property<double>("InterestRate")
                        .HasColumnType("float");

                    b.Property<double>("ManufacturingPMI")
                        .HasColumnType("float");

                    b.Property<double>("RetailPositionScore")
                        .HasColumnType("float");

                    b.Property<double>("SeasonalityScore")
                        .HasColumnType("float");

                    b.Property<double>("ServicesPMI")
                        .HasColumnType("float");

                    b.Property<double>("TrendScore")
                        .HasColumnType("float");

                    b.Property<double>("UnemploymentRate")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("IndicatorData");
                });

            modelBuilder.Entity("TradeHelper.Models.Instrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instruments");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            AssetClass = "ForexMajor",
                            Name = "EURUSD",
                            Type = "Currency"
                        },
                        new
                        {
                            Id = 101,
                            AssetClass = "ForexMajor",
                            Name = "GBPUSD",
                            Type = "Currency"
                        },
                        new
                        {
                            Id = 102,
                            AssetClass = "ForexMajor",
                            Name = "USDJPY",
                            Type = "Currency"
                        },
                        new
                        {
                            Id = 103,
                            AssetClass = "ForexMajor",
                            Name = "USDCHF",
                            Type = "Currency"
                        },
                        new
                        {
                            Id = 104,
                            AssetClass = "ForexMajor",
                            Name = "AUDUSD",
                            Type = "Currency"
                        },
                        new
                        {
                            Id = 105,
                            AssetClass = "ForexMajor",
                            Name = "USDCAD",
                            Type = "Currency"
                        },
                        new
                        {
                            Id = 106,
                            AssetClass = "ForexMajor",
                            Name = "NZDUSD",
                            Type = "Currency"
                        },
                        new
                        {
                            Id = 107,
                            AssetClass = "ForexMajor",
                            Name = "GBPJPY",
                            Type = "Currency"
                        },
                        new
                        {
                            Id = 108,
                            AssetClass = "ForexMinor",
                            Name = "EURGBP",
                            Type = "Currency"
                        },
                        new
                        {
                            Id = 109,
                            AssetClass = "ForexMinor",
                            Name = "EURJPY",
                            Type = "Currency"
                        },
                        new
                        {
                            Id = 110,
                            AssetClass = "ForexMinor",
                            Name = "EURCHF",
                            Type = "Currency"
                        },
                        new
                        {
                            Id = 111,
                            AssetClass = "ForexMinor",
                            Name = "EURAUD",
                            Type = "Currency"
                        },
                        new
                        {
                            Id = 112,
                            AssetClass = "ForexMinor",
                            Name = "EURCAD",
                            Type = "Currency"
                        },
                        new
                        {
                            Id = 113,
                            AssetClass = "ForexMinor",
                            Name = "EURNZD",
                            Type = "Currency"
                        },
                        new
                        {
                            Id = 114,
                            AssetClass = "ForexMinor",
                            Name = "GBPCHF",
                            Type = "Currency"
                        },
                        new
                        {
                            Id = 115,
                            AssetClass = "ForexMinor",
                            Name = "GBPAUD",
                            Type = "Currency"
                        },
                        new
                        {
                            Id = 116,
                            AssetClass = "ForexMinor",
                            Name = "GBPCAD",
                            Type = "Currency"
                        },
                        new
                        {
                            Id = 117,
                            AssetClass = "ForexMinor",
                            Name = "GBPNZD",
                            Type = "Currency"
                        },
                        new
                        {
                            Id = 118,
                            AssetClass = "ForexMinor",
                            Name = "AUDJPY",
                            Type = "Currency"
                        },
                        new
                        {
                            Id = 119,
                            AssetClass = "ForexMinor",
                            Name = "AUDCHF",
                            Type = "Currency"
                        },
                        new
                        {
                            Id = 120,
                            AssetClass = "ForexMinor",
                            Name = "AUDCAD",
                            Type = "Currency"
                        },
                        new
                        {
                            Id = 121,
                            AssetClass = "ForexMinor",
                            Name = "AUDNZD",
                            Type = "Currency"
                        },
                        new
                        {
                            Id = 122,
                            AssetClass = "ForexMinor",
                            Name = "NZDJPY",
                            Type = "Currency"
                        },
                        new
                        {
                            Id = 123,
                            AssetClass = "ForexMinor",
                            Name = "NZDCHF",
                            Type = "Currency"
                        },
                        new
                        {
                            Id = 124,
                            AssetClass = "ForexMinor",
                            Name = "NZDCAD",
                            Type = "Currency"
                        },
                        new
                        {
                            Id = 125,
                            AssetClass = "ForexMinor",
                            Name = "CADJPY",
                            Type = "Currency"
                        },
                        new
                        {
                            Id = 126,
                            AssetClass = "ForexMinor",
                            Name = "CADCHF",
                            Type = "Currency"
                        },
                        new
                        {
                            Id = 127,
                            AssetClass = "ForexMinor",
                            Name = "CHFJPY",
                            Type = "Currency"
                        },
                        new
                        {
                            Id = 128,
                            AssetClass = "ForexMinor",
                            Name = "USDSEK",
                            Type = "Currency"
                        },
                        new
                        {
                            Id = 129,
                            AssetClass = "Index",
                            Name = "US500",
                            Type = "Commodity"
                        },
                        new
                        {
                            Id = 130,
                            AssetClass = "Index",
                            Name = "US30",
                            Type = "Commodity"
                        },
                        new
                        {
                            Id = 131,
                            AssetClass = "Index",
                            Name = "US100",
                            Type = "Commodity"
                        },
                        new
                        {
                            Id = 132,
                            AssetClass = "Index",
                            Name = "DE40",
                            Type = "Commodity"
                        },
                        new
                        {
                            Id = 133,
                            AssetClass = "Index",
                            Name = "UK100",
                            Type = "Commodity"
                        },
                        new
                        {
                            Id = 134,
                            AssetClass = "Index",
                            Name = "JP225",
                            Type = "Commodity"
                        },
                        new
                        {
                            Id = 135,
                            AssetClass = "Metal",
                            Name = "XAUUSD",
                            Type = "Commodity"
                        },
                        new
                        {
                            Id = 136,
                            AssetClass = "Metal",
                            Name = "XAGUSD",
                            Type = "Commodity"
                        },
                        new
                        {
                            Id = 137,
                            AssetClass = "Metal",
                            Name = "XPTUSD",
                            Type = "Commodity"
                        },
                        new
                        {
                            Id = 138,
                            AssetClass = "Metal",
                            Name = "XPDUSD",
                            Type = "Commodity"
                        },
                        new
                        {
                            Id = 139,
                            AssetClass = "Commodity",
                            Name = "USOIL",
                            Type = "Commodity"
                        },
                        new
                        {
                            Id = 140,
                            AssetClass = "Bond",
                            Name = "US10Y",
                            Type = "Commodity"
                        });
                });

            modelBuilder.Entity("TradeHelper.Models.Strategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Strategies");
                });

            modelBuilder.Entity("TradeHelper.Models.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Broker")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DisplayCurrencySymbol")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("decimal(18,5)");

                    b.Property<DateTime?>("ExitDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ExitPrice")
                        .HasColumnType("decimal(18,5)");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("LotSize")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ProfitLoss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ProfitLossDisplay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RiskReward")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("StopLoss")
                        .HasColumnType("decimal(18,5)");

                    b.Property<int?>("StrategyId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TakeProfit")
                        .HasColumnType("decimal(18,5)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("TradeHelper.Models.TradeImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TradeId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("TradeId");

                    b.ToTable("TradeImages");
                });

            modelBuilder.Entity("TradeHelper.Models.UserLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UserLogs");
                });

            modelBuilder.Entity("TradeHelper.Models.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DisplayCurrencySymbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TradeHelper.Models.EdgeFinderScore", b =>
                {
                    b.HasOne("TradeHelper.Models.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("TradeHelper.Models.Trade", b =>
                {
                    b.HasOne("TradeHelper.Models.Strategy", "Strategy")
                        .WithMany("Trades")
                        .HasForeignKey("StrategyId");

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("TradeHelper.Models.TradeImage", b =>
                {
                    b.HasOne("TradeHelper.Models.Trade", "Trade")
                        .WithMany("TradeImages")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("TradeHelper.Models.Strategy", b =>
                {
                    b.Navigation("Trades");
                });

            modelBuilder.Entity("TradeHelper.Models.Trade", b =>
                {
                    b.Navigation("TradeImages");
                });
#pragma warning restore 612, 618
        }
    }
}
